version: '3'

services:
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_DB: nakama
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localdb
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  nakama:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    entrypoint:
      - /bin/sh
      - -ecx
      - |
        /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
        exec /nakama/nakama --database.address postgres:localdb@postgres:5432/nakama
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"

  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    depends_on:
      - nakama
    environment:
      TEST: true
    entrypoint: [ "/bin/sh", "-c", "while ! curl -sSf http://nakama:7350/healthcheck; do echo 'Waiting for Nakama to be ready...'; sleep 5; done && go test -v main_e2e_test.go" ]

volumes:
  data:
